apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-rest
  name: udaconnect-location-rest
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30005
  selector:
    service: udaconnect-location-rest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-rest
  name: udaconnect-location-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-rest
  template:
    metadata:
      labels:
        service: udaconnect-location-rest
    spec:
      containers:
      - image: yoram460/udaconnect-location-rest:latest
        name: udaconnect-location-rest
        imagePullPolicy: Always
        env:
        - name: TOPIC_LOCATION
          value: create_location_events
        - name: KAFKA_SERVER
          value: udaconnect-kafka:9092
      restartPolicy: Always
